### ISSUE TITLE
driver install document inconsistency

### ISSUE THREAD

**Issue by bigeetea** [torayeff/fanucpy#10]
In section 2.1.1 you are referencing $HOSTS_CFG

However, in the screenshot in section 2.1.3 you are showing $HOSTC_CFG

Which is it?

**Comment by bigeetea** [comment]
Also, will this run on V7.2 Fanuc controller?  The main difference I am seeing is you can't specify a port # on the TAGS screen

**Comment by mf093087** [comment]
Hi, thanks a lot for contacting us. It is $HOSTS_CFG. We have updated the photos. Regarding the V7.2 Fanuc controller, we haven't checked it physically. We will come back to you once we checked the controller physically. If you have any further questions, feel free to contact us.

**Comment by bigeetea** [comment]
Thank you for fixing the driver install doc.  I have been trying to get KTRANS to build the drivers using /ver V7.20-1, and I have found several issues.  Issues I've found thus far that I am trying to fix:

names longer than 12 characters -- easy fix.
STRING[254] -- error says String can't be longer than 128 -- even after fixing this remains an issue at the moment.

Also, mappdk_cmd, and mappdk_comm don't build because there is no Program defined, only Routines.

**Comment by torayeff** [comment]
You cannot build mappdk_cmd and mappdk_comm. Instead build mappdk_server and mappdk_logger.

**Comment by bigeetea** [comment]
Thank you for your assistance.  I was able to get the software to run (User screen says MAPPDK SERVER started) inside of my HandlingPro Cell.  However, since this is a virtual device, is there a networking trick I need to use so my Python program on my localhost can connect to the virtual controller running inside of Roboguide?

**Comment by torayeff** [comment]
There is no need for networking trick. Just connect to the IP address 127.0.0.1 from Python API. That’s all :)

**Comment by torayeff** [comment]
I will close the issue if your problem is solved.

**Comment by bigeetea** [comment]
thank you.  yes, you can close this issue.
