### ISSUE TITLE
null response to commands other than .connect()

### ISSUE THREAD

**Issue by bigeetea** [torayeff/fanucpy#12]
![image](https://user-images.githubusercontent.com/9824148/170845268-a7fe080c-6da4-4952-badf-5f4ae66d7745.png)

I am having a problem running on V7.20-1 Controller.  The Robot Controller is not returning a response for methods other than connect().

Take a look at the screen shot and you will see the "curpos" command and empty response:

cmd.encode(): b'curpos\n'
resp:

The empty response is what is causing the exception when trying to split(":")

I have tried many things, but nothing seems to get a response.

Any ideas?

FYI - the success line at the top of the screen shot is the call to connect() .. and the Robot2 class is my copy of your class just with some print statements for debugging

**Comment by torayeff** [comment]
Can you please try decreasing string length from 254 to 128 in all of the .kl files? I assume that might be the problem for controller versions v7.x

**Comment by bigeetea** [comment]
Yes - I forked your project and fixed all the build errors for V7.2  i.e. class or variable names longer than 12 chars and strings set to 128.  The software is definitely running on the Robot Controller, and the .connect() method appears to work, however other commands (move, curpos, curjpos, etc) don't move the robot and don't return a response.

**Comment by torayeff** [comment]
Can you try this simple command:
`print(f"Get gripper state: {robot.get_rdo(7)}")`

We can start debugging from there.

**Comment by bigeetea** [comment]
same result -- I have attached sample code and stacktrace

![image](https://user-images.githubusercontent.com/9824148/170846745-e566d1c0-3c67-4765-be76-55899a14a518.png)

![image](https://user-images.githubusercontent.com/9824148/170846746-cfb4ec7b-a380-4295-aec1-91259bfa20cf.png)

**Comment by bigeetea** [comment]
No difference if when I use your main branch directly -- sample code --

![image](https://user-images.githubusercontent.com/9824148/170846882-45a5d688-0f47-4939-8a68-86ec4269a110.png)

![image](https://user-images.githubusercontent.com/9824148/170846889-7f9b2714-ad5c-4ce7-a86d-3907934430eb.png)

**Comment by bigeetea** [comment]
![image](https://user-images.githubusercontent.com/9824148/170847037-3309bbaf-b3bf-4e31-807b-ea4bd9540a5b.png)

![image](https://user-images.githubusercontent.com/9824148/170847064-b73c3285-1bcc-4542-b0cc-b964a3d69def.png)

The only difference I have found between your instructions and my v7.2 controller is:  No ability to set port number on Server Tag:

![image](https://user-images.githubusercontent.com/9824148/170847102-37e29076-7461-46da-9880-4ec0298d0d01.png)

**Comment by torayeff** [comment]
Can you add the following command on line 66 in mappdk_server.kl:
`WRITE(resp, CR)`
It will output the resp on teach pendant. Let’s see whether we can get the output there.

**Comment by bigeetea** [comment]
Where should I see the output?  Should it be on the User screen under the sentence "MAPPDK SERVER started" ??  Because I"m not seeing anything on the User screen:

![image](https://user-images.githubusercontent.com/9824148/170847537-73f91bea-74dc-4665-852b-7bf94dff20e9.png)

For reference, here is all I changed in my fork to make your project compile and run on V7.2

https://github.com/bigeetea/fanucpy/pull/2/files

**Comment by torayeff** [comment]
Whenever you run any command from python, it should be visible after MAPPDK SERVER started.

**Comment by bigeetea** [comment]
you said python in your last comment.. I think you meant Karel since we're still talking about mappdk_server.kl .... correct?

**Comment by bigeetea** [comment]
I figured out why I didn't see anything on the User screen... we aren't taking the ELSE side of the logic:

![image](https://user-images.githubusercontent.com/9824148/170848303-4e334c3f-9257-4251-9e95-85b02b6f7426.png)

**Comment by bigeetea** [comment]
cmd is definitely uninitialized

![image](https://user-images.githubusercontent.com/9824148/170848545-1871e1f4-0de1-4486-8d0c-24a4d724a7f7.png)

**Comment by torayeff** [comment]
You should put:
`WRITE("RESP:", resp, CR)` 
here: 
https://github.com/torayeff/fanucpy/blob/1a2141af4abaceac82b93738e815982b9bda228f/src/fanuc-driver/mappdk_server.kl#L66

Then call Python command such as:
`print(f"Get gripper state: {robot.get_rdo(7)}")`

Please check if the above works and we can continue debugging from there.

**Comment by bigeetea** [comment]
same result .. nothing except "MAPPDK SERVER started" is ever printed .. the reason is because we never run line # 66

the reason is because cmd is uninitialized, so we never go into the ELSE side of that logic.. it always runs line # 62 and # 63

            IF UNINIT(cmd) THEN
                keep_conn = FALSE

**Comment by bigeetea** [comment]
I believe the problem is something inside of mappdk_comm.kl OPEN_COMM method... it has something to do with line # 48

MSG_CONNECT(server_tag, status)

...something isn't happening correctly with that upon startup

I'd be happy to share my screen via zoom and pair debug this issue if you'd like.

**Comment by torayeff** [comment]
Drop me email at torayeff@gmail.com

**Comment by torayeff** [comment]
It seems there is a small typo in this [line](https://github.com/torayeff/fanucpy/blob/1a2141af4abaceac82b93738e815982b9bda228f/src/fanuc-driver/mappdk_comm.kl#L40). Can you please also change it to:
`'$HOSTS_CFG[' + server_str + '].$SERVER_PORT'`
