### ISSUE TITLE
Publishing to pypi

### ISSUE THREAD

**Issue by ZdenekM** [torayeff/fanucpy#2]
Good job! I'm just wondering - is there a plan to publish this stuff to PyPI, so one can install it using pip? Thanks.

**Comment by torayeff** [comment]
Thanks! Today or tomorrow!

**Comment by ZdenekM** [comment]
Glad to hear that. We will try to use it to integrate Fanuc robots into the framework for AR-based robot programming (check https://github.com/robofit/arcor2 if it is interesting for you).

**Comment by torayeff** [comment]
@ZdenekM, our group also develops apps for robots. Let me know if you have any suggestions/difficulties with this library. It will be interesting to collaborate and come up with novel industrial applications.

**Comment by torayeff** [comment]
Package released https://pypi.org/project/fanucpy/

**Comment by ZdenekM** [comment]
Thanks for releasing it. I got a little bit distracted by some other stuff, but I will get back to working with the Fanuc robot soon. Regarding the functionality of the library, would it be possible to add methods for IK and FK?

I have seen the web of your institute and it looks really interesting. If you would ever need a partner for a project with experience in AR, VR, HRI, UX, etc., we are definitely open to all ideas.

**Comment by torayeff** [comment]
@ZdenekM, we are working on adding more functionalities. Thank you very much for your interest, and it would be interesting to work and collaborate on a common project.

**Comment by ZdenekM** [comment]
> we are working on adding more functionalities

And is particularly IK/FK (`Pos2Joint` and `Joint2Pos`) something you are working on?

**Comment by torayeff** [comment]
Not custom IK/FK particularly, but more on modularization that will allow adding external IK solvers.

**Comment by ZdenekM** [comment]
I actually meant making the existing functionality of `Pos2Joint` and `Joint2Pos` Karel commands accessible through Python - in order to get IK/FK from the robot.

**Comment by ZdenekM** [comment]
That would be probably the easiest way to get IK/FK. What do you think? However I have no experience with those commands so far, so maybe I'm missing something important.

**Comment by torayeff** [comment]
You are right. It should be relatively straightforward. One can easily add those commands to this file https://github.com/torayeff/fanucpy/blob/main/src/fanuc-driver/mappdk_cmd.kl

**Comment by torayeff** [comment]
Let me think about the interface for integrating any built-in function.

**Comment by torayeff** [comment]
It seems that POS2JOINT requires extra parameters such as the reference joint angles that represent the robot's position just before moving to the current position. Let me know if you think we can do it in a smarter way.
