### ISSUE TITLE
Joint velocities and accelerations

### ISSUE THREAD

**Issue by juhannc** [torayeff/fanucpy#26]
Is it possible, to get the current joint velocities and accelerations similar to `robot.get_curjpos`?
Is there maybe a custom command one can send or a routine one can define?

Thank you

**Comment by torayeff** [comment]
@juhannc not implemented at this point. But if you know which system variable holds the acceleration and velocity value, you can write a wrapper.

**Comment by gavanderhoorn** [comment]
Access to dynamics and related state information is just not something that's really available on Fanucs. Additionally, the low rate at which the Karel VM is running would lead to rather noisy data in any case. Especially the higher derivatives.

Other robot brands might be easier to work with.

**Comment by juhannc** [comment]
@gavanderhoorn thanks for the heads-up, appreciate it!
Sadly though, using the fanuc wasn't my choice but I'm stuck with it for now :/

**Comment by gavanderhoorn** [comment]
> using the fanuc wasn't my choice but I'm stuck with it for now :/

yes, that's typically how it happens.

If you have the option, try looking into `J519` (or: *Stream Motion*) or `R891` (or: *High Speed Position Output*).

If you do find some system variables that contain (the) information you're interested in, at least one of those options should allow you to retrieve their values at much higher rates and with much less jitter than any Karel program would ever be able to.

**Comment by juhannc** [comment]
Awesome, thank you! Will look into it!
