### ISSUE TITLE
Connectivity issue

### ISSUE THREAD

**Issue by nilic993** [torayeff/fanucpy#3]
Hi torayeff, I'm having trouble sending commands to my Fanuc robot through MAPPDK. I'm fairly certain it has little to do with your driver and more with network communication, but maybe you've ran into similar issues while coding or testing the driver.

I went through all of the instructions in the FANUC MAPPDK Driver readme, and MAPPDK is (apparently) running fine on my controller. The only part I've skipped is the logger on port 18736 (for now). The robot (CRX-10ia) and the laptop from which I want to issue commands through fanucpy (an Ubuntu machine) are in the same subnet, with IPs ending with .10 and .100 as in the readme. I've disabled DHCP via the teach pendant.

With all that set up, I try running a sample python file to send a command to the robot and get this error:

File "/home/wherever my script is/test.py", in connect
self.comm_sock.connect((self.host, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

The machines see each other and can ping between them.

**Comment by torayeff** [comment]
When you run MAPPDK on robot controller, it automatically starts both MAPPDK_SERVER and MAPPDK_LOGGER. Can you please share the following details:

1. Does teach pendant display that both services has started?
2. Which command is the reason for error?
3. In which mode is robot controller (Auto, T1, T2)?

I usually put the robot on Auto mode and press cycle start on robot controller to start both services.

**Comment by nilic993** [comment]
1. As far as I can tell only the SERVER is running, because I've started the program from the file list on the teach pendant
2. The robot.connect() command, the error is returned immediately so I don't think that there's even a proper attempt to establish communication
3. I don't have a switchbox with my arm so I'm assuming it's locked into T1 mode

Here's how running MAPPDK looks on my pendant:

![p](https://user-images.githubusercontent.com/55019479/163803313-80f07bbb-88d2-470c-8e3a-2a640561b8bd.jpg)

At any rate I'm probably not launching MAPPDK correctly, I transferred the files to the controller and I'm launching the mappdk_server.pc file.

**Comment by torayeff** [comment]
One problem might be with the server setup. Can you please double-check that the port on your robot controller is **18735** and server tag is **8**?

**Comment by nilic993** [comment]
![1](https://user-images.githubusercontent.com/55019479/163975277-454dab21-dd53-4b09-a7af-4b6282a4d0cb.jpg)

This looks right to me. There definitely is some kind of connection (which is being refused), because I get a different error (113: No Route to Host) when I unplug the ethernet cable.

**Comment by torayeff** [comment]
Can you please drop me a message via torayeff@gmail.com? We can arrange a video call to resolve this issue.

**Comment by matteotagliavini** [comment]
Hi, I have the same connectivity problem.
In particular, i can't load the ".ls" extension file (mappdk.ls).
Any suggestion?
Thank You.

**Comment by torayeff** [comment]
Can you please elaborate more on not being able to load ".ls" extension file? What errors do you get?

**Comment by matteotagliavini** [comment]
![fanuc](https://user-images.githubusercontent.com/57959548/207555344-f2585f78-8c18-4861-b7c0-5f6ce880651d.jpeg)

This is the error when i try to load  file "MPPDK.ls " from USB device (downloaded from your repository).

I also realized that I only have the R648(User Socket Messaging) modules on ​​the controller. Can I communicate with the robot via Python script only with User Socket Messaging or do I need the R632(Karel) modules?

Thank you.

**Comment by torayeff** [comment]
If you cannot load, then just creat a TP program with the following 2 lines:
```
RUN MAPPDK_SERVER
RUN MAPPDK_LOGGER
```

I think some controllers do not show the availability of R632 but it is available by default. So you should be ok.

**Comment by gavanderhoorn** [comment]
@matteotagliavini: your controller doesn't have the `Ascii Upload` option. That's why you can't load the `.ls`.

**Comment by matteotagliavini** [comment]
![server_logger](https://user-images.githubusercontent.com/57959548/207591808-5d77c459-90da-4f6f-a8f4-f9b1df474b47.jpeg)

![image](https://user-images.githubusercontent.com/57959548/207591693-69c61b86-635c-4caf-bba8-3a57f74e2cd2.png)


@torayeff 
These are my screens. Loggers and servers seem to be working. When i try to connect with python the connection fails (italian).
(192.168.0.1 is the IP address I configured on the controller while following your guide)

**Comment by torayeff** [comment]
@matteotagliavini Can you please confirm that your computer and robot in the same network? What is your local IP?

Do they follow the same subnet, i.e.,
```
Robot Controller: 192.168.0.1
Your PC: 192.168.0.X
```

**Comment by matteotagliavini** [comment]
Yes, i connect PC and Robot with Ethernet cable. Should i connect them with a Switch or router ?

Thanks.

**Comment by torayeff** [comment]
If you don’t mind can you paste the output of cmd command IPCONFIG?

**Comment by matteotagliavini** [comment]
![image](https://user-images.githubusercontent.com/57959548/207599145-b791fc17-f64d-4989-a453-f5bb974aba2b.png)

**Comment by torayeff** [comment]
Ok. I see it. Can you please change the robot controller IP address to `192.168.0.63` and if that does not work drop me an email and we can arrange a zoom call.

**Comment by matteotagliavini** [comment]
@torayeff 
Thank you so much for the advice. I configured the robot through the router and now I can connect PC and Robot. But when i try to make a move instruction via python (robot.move() ), the TP gives me error "call program failed".
Any advice?

**Comment by torayeff** [comment]
@matteotagliavini You are welcome. This might be because of the following:
1. You are running the script in T1/T2 mode. In that case, you need to either switch to Auto mode or keep pressing the deadman switch on the teach pendant.
2. You might be missing the **mappdk_movel.ls** and **mappdk_move.ls** files.

Let me know how it goes.

**Comment by matteotagliavini** [comment]
@torayeff 
Yes now the movements work too. I had to convert the files you told me to .TP format because our controller doesn't load .LS format as i mentioned before.
Thank you so much bro.

**Comment by torayeff** [comment]
@matteotagliavini, you are welcome. I am closing the issue.

**Comment by torayeff** [comment]
Hi! Try the localhost ip 127.0.0.1 for the roboguide connection.

**Comment by madinwei** [comment]
> Hi! Try the localhost ip 127.0.0.1 for the roboguide connection.

@torayeff Thank you so much it worked with the default IP. but after I check the TCP/IP I understand that the init button doesn't save any change, so that is the reason, how I can fix it if you have any idea, here is a screenshot:
![image](https://github.com/torayeff/fanucpy/assets/120000071/74896a1a-7514-416a-881b-fc4afa216d53)
as you see in the pic, ethernet init fail so how I can fix it?

**Comment by torayeff** [comment]
“Ethernet init fail” also happens with me every time when I use roboguide. Despite that it works alright with me. Honestly, I have no idea why it behaves that way 🤦‍♂️
