### ISSUE TITLE
Problem with (MAPPDK_Server, 204) uninit

### ISSUE THREAD

**Issue by abouju64** [torayeff/fanucpy#33]
Hello,

I send you a vidéo of my problem. I can communicated with the robot but when i need to move an error appear. 

Sincerely, 
Antoine.

https://github.com/torayeff/fanucpy/assets/149599305/8a9491fe-3736-4aa9-818a-c358ac671f49

**Comment by torayeff** [comment]
@abouju64 I am aware of this error. Can you please for now, use the Python code from here https://github.com/torayeff/robominder/blob/main/robominder/fanuc.py

**Comment by tommbern** [comment]
Hi, I've been using this package lately and have encountered the same issue. "move.robot("pose") was crashing my program.
Setting "linear=true" seems to solve the problem.

@torayeff the CHECK_EPOS() Karel command in the move("pose") routine (mappdk_cmd.kl) kept sending me errors for position-not-reachable even though the position was in fact reachable by moving the Fanuc robot in jog-mode.
Have you tried using the Karel command IN_RANGE()?

**Comment by torayeff** [comment]
Fixed in new version v0.1.14. Please install the latest from pypi.
