### ISSUE TITLE
Missing dependency on sqlalchemy in pyproject.toml

### ISSUE THREAD

**Issue by ZdenekM** [torayeff/fanucpy#7]
Version 0.1.6 imports `sqlalchemy` (see https://github.com/torayeff/fanucpy/commit/fdf76dd1ae8d3f788875127cfb1fe8c8f637eced#diff-0f3271fd54afd0487ac6855d92f2de5bf8d815b81d9e70a5eb8f3f7c0d1ed229R5), but the dependency is not declared in `pyproject.toml`.

**Comment by torayeff** [comment]
Somehow sqlalchemy got imported by mistake. I fixed it now.
